### ISSUE TITLE
Directory path for the agent configuration incorrectly defaults to `/etc`

### ISSUE THREAD

**Issue by djcoster** [newrelic/infrastructure-agent-chef#110]
## Description
The README.md claims the default value for `default['newrelic_infra']['agent']['directory']['path']` is `/etc/newrelic-infra`, when the `attributes/default.rb` file contains.

```
default['newrelic_infra']['agent'].tap do |conf|
  conf['config']['file'] = 'newrelic-infra.yml'
  conf['config']['mode'] = '0640'
  conf['directory']['path'] = '/etc/'
end
```

This sets it to `/etc/` and not the correct value. This also has the _very_ undesirable effect of changing `owner` and `group` of `/etc` to be the `newrelic_infra` user and group.

## Expected Behavior
The default path should be `/etc/newrelic-infra` as documented in the README file.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
Snippet from `chef-client` execution using the default value for the attribute.

```           * apt_package[newrelic-infra] action install
             - install version 1.20.3 of package newrelic-infra
           * execute[reload_initctl_conf] action run (skipped due to only_if)
           * directory[/etc/] action create
             - change owner from 'root' to 'newrelic_infra'
             - change group from 'root' to 'newrelic_infra'
           * file[/etc/newrelic-infra.yml] action create
             - create new file /etc/newrelic-infra.yml
             - update content in file /etc/newrelic-infra.yml from none to 967b8e
             - suppressed sensitive resource
             - change mode from '' to '0640'
             - change owner from '' to 'newrelic_infra'
             - change group from '' to 'newrelic_infra'
```

Also notice that the `newrelic-infra.yml` file is incorrectly located in `/etc` as well.

## Steps to Reproduce
Create a simple Policy file that calls a cookbook recipe with a single call to `include_recipe 'newrelic-infra'` on a Linux system.

## Your Environment
Can reproduce this using test kitchen with:

```
platforms:
  - name: ubuntu-18.04
```

**Comment by haidangwa** [comment]
The template examples for NR Infrastructure Agent also specifiy `/etc/newrelic-infra.yml` as the name of the agent config file. https://github.com/newrelic/infrastructure-agent/blob/master/assets/examples/infrastructure/newrelic-infra-template.yml.example#L9

**Comment by haidangwa** [comment]
New Relic's online documentation also specify `/etc/newrelic-infra.yml` to configure the agent: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent/#config-file

With all the documentation pointing at `/etc/newrelic-infra.yml` as the location to configure the agent, doesn't it make sense for chef to NOT change the owner and group for `/etc`? Besides, in [this chef resource](https://github.com/newrelic/infrastructure-agent-chef/blob/master/recipes/agent_linux.rb#L139-L150), the configuration file is hardcoded, which should be a separate chef bug, as it ignores the cookbook attribute, `node['newrelic_infra']['agent']['config']['file']`.

**Comment by pborowicz** [comment]
This seems like an easy fix. I have a workaround for now, but any ETA on when this might be fixed? Does it effect Ubutnu 20.04?

**Comment by djcoster** [comment]
> Does it effect Ubutnu 20.04?

The bug is not related to the version of the OS and will effect Ubuntu 20.04 as well.

**Comment by djcoster** [comment]
> New Relic's online documentation also specify `/etc/newrelic-infra.yml` to configure the agent: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent/#config-file

As stated in the description, the README does not specify that for configuring the agent. This means that the cookbook is not consistent with other online documentation and a resolution to this bug could be to update the README and fix the permissions issue as you mentioned.

**Comment by odlevakp** [comment]
I don't mind the placement of the config file, but what bothers me is a default behaviour under which `/etc` ownership is changed from root to NR user, that's just bad and insecure.
