### ISSUE TITLE
Add retries to package resource?

### ISSUE THREAD

**Issue by ajkerr** [newrelic/infrastructure-agent-chef#28]
We are getting periodic failures during the provisioning of our EC2 instances. The issue happens when this cookbook attempts to install the newrelic-infra package.

The error is the "Could not get lock /var/lib/dpkg/lock" issue that pops up on Ubuntu from time to time. We haven't been able to track down what is locking that file during our Chef runs.

A simple fix would be to add a "retries" property to the package resource statement that installs newrelic-infra. This could also be configurable as an attribute.

**Comment by smith** [comment]
@ajkerr let me know if #29 does what you need. Thanks for suggesting it!

**Comment by ajkerr** [comment]
@smith That's looks awesome, exactly what I was hoping for. Thanks for the quick turnaround!

**Comment by Firefishy** [comment]
The issue is newrelic-infra runs factor which queries installed apt packages, which in-turn locks the apt database during query. Any apt packages installs then block.
