### ISSUE TITLE
logrotate setup for logfile

### ISSUE THREAD

**Issue by akshah123** [newrelic/infrastructure-agent-chef#34]
I don't see a way to setup logrotate for log file in the chef cookbook.

It would be really useful if logfile setup automatically took care of creating the folder and setting up rotation.

**Comment by smith** [comment]
This would be nice, but we don't have any plans to implement it. The [logrotate cookbook](https://supermarket.chef.io/cookbooks/logrotate) provides a good resource to easily do this.
