### ISSUE TITLE
the new relic pem key is confusing chef

### ISSUE THREAD

**Issue by rreilly-edr** [newrelic/infrastructure-agent-chef#35]
Hi, the encrypted new relic key seems to be confusing berks ? I cloned the repository ran berks install and get the following error when running berks upload
```
E, [2018-05-11T09:03:23.494630 #24654] ERROR -- : Ridley::Errors::ClientKeyFileNotFoundOrInvalid: client key is invalid or not found at: '/home/rreilly/chef-repo/cookbooks/newrelic.pem'
```

**Comment by rreilly-edr** [comment]
Ahh, I  see .chef directory is included in the repo, maybe add it to an ignore file probably dont want to distribute your chef key.

**Comment by smith** [comment]
The key is not distributed in the repo, but the .chef directory is there so Travis can deploy releases to Supermarket. .chef is in chefignore, so the artifact that's distributed does not include this directory.

You shouldn't need to berks upload from the repo unless you're in an environment where you cannot access the public supermarket.

If you do need to berks upload, you should be able to override the default settings to look for another config file.
