### ISSUE TITLE
Suggestion to Implement Release / Tagging

### ISSUE THREAD

**Issue by brandonpiercenb** [newrelic/infrastructure-agent-chef#4]
The reported version in the cookbook metadata is `0.0.1` ever since the initial commit despite the fact that there have been various changes/additions/etc. In order to support a more stable distribution of this cookbook would it be possible to incorporate bumping that version and tagging the repo for releases?

In lieu of that the following type of setup must be done in the `Berksfile` of our cookbooks that depend on this:

```ruby
source 'https://supermarket.chef.io'

# lock to a specific commit since cookbook isn't currently tagging releases
cookbook('newrelic-infra',
         git: 'git@github.com:newrelic/infrastructure-agent-chef.git',
         ref: 'b4f3f534faea587971ad5c5e4572d9393e11877c')
         
metadata
```

On a related note, these releases could (should?) be upload to the Supermarket to help further ease distribution.

```none
Resolving cookbook dependencies...
Fetching 'consuming-cookbook' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Unable to satisfy constraints on package newrelic-infra, which does not exist, due to solution constraint (consuming-cookbook = 1.1.0). Solution constraints that may result in a constraint on newrelic-infra: [(consuming-cookbook = 1.1.0) -> (newrelic-infra ~> 0.0.1)]
Missing artifacts: newrelic-infra
Demand that cannot be met: (consuming-cookbook = 1.1.0)
Unable to find a solution for demands: consuming-cookbook (1.1.0)
```

**Comment by chaupt** [comment]
@brandonpiercenb Good suggestions. 

We'll add a note to the readme to start bumping the build number at the least. 

We've been looking at the Supermarket path as well for the future.

**Comment by smith** [comment]
@brandonpiercenb 100% percent on board. I've set up a project for the 1.0.0 release that includes this: https://github.com/newrelic/infrastructure-agent-chef/projects/1

Closing this issue.

**Comment by brandonpiercenb** [comment]
Sweet - thank you @chaupt 🤘
