### ISSUE TITLE
license_key should probably be gotten from an (encrypted) data bag

### ISSUE THREAD

**Issue by docwhat** [newrelic/infrastructure-agent-chef#52]
I'm assuming the `license_key` is a secret.

If so, it should probably be stored in an encrypted data bag by default, no?

You can store the name of the databag and the databag item name as two attributes:

- `default['newrelic_infra']['config']['databag']`
- `default['newrelic_infra']['config']['databag-item']`

Within that databag item it could be stored as `license_key`.

**Comment by alejandrodnm** [comment]
Hi @docwhat we'll take a look at it and let you know, thanks.

**Comment by alejandrodnm** [comment]
Hi @docwhat, sorry this is not in our current roadmap, and I don't think is going to be tackled anytime soon. Sorry for the late response, but we've been trying to fit this in our planning and ended up always moving it. 

We encourage you to submit a PR to fix this issue :)
