### ISSUE TITLE
Breaking Change on latest Release - Undefined Method 'any?'

### ISSUE THREAD

**Issue by josephjonko** [newrelic/infrastructure-agent-chef#54]
NoMethodError
  -------------
  undefined method `any?' for false:FalseClass
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/newrelic-infra/recipes/host_integrations.rb:12:in `from_file'
    /var/chef/cache/cookbooks/newrelic-infra/recipes/agent_linux.rb:103:in `from_file'
    /var/chef/cache/cookbooks/newrelic-infra/recipes/default.rb:11:in `from_file'
    /var/chef/cache/cookbooks/mb_newrelic/recipes/default.rb:29:in `from_file'
    /var/chef/cache/cookbooks/mb_monitoring/recipes/default.rb:2:in `from_file'
    /var/chef/cache/cookbooks/role_logstash/recipes/default.rb:8:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/newrelic-infra/recipes/host_integrations.rb:
  
    5:  #
    6:  
    7:  #
    8:  # Installs New Relic provided and custom on-host integrations
    9:  #
   10:  
   11:  # Install host integrations defined with attributes
   12>> if node['newrelic_infra']['features']['host_integrations'].any?
   13:    node['newrelic_infra']['features']['host_integrations'].each do |integration_name|
   14:      package integration_name do
   15:        action node['newrelic_infra']['packages'][integration_name]['action']
   16:        retries node['newrelic_infra']['packages'][integration_name]['retries']
   17:        version node['newrelic_infra']['packages'][integration_name]['version'].to_s
   18:      end
   19:    end
   20:  
   21:    directory node['newrelic_infra']['host_integrations']['config_dir'] do
  
  System Info:
  ------------
  chef_version=13.8.5
  platform=redhat
  platform_version=7.3
  ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
  program_name=chef-client worker: ppid=18266;start=11:00:12;
  executable=/opt/chef/bin/chef-client

**Comment by alejandrodnm** [comment]
Hi @josephjonko, a breaking change was introduced for version `0.9.0`, `hosthost_integrations` changes from a boolean to an array. From what I can see from your error message, you have it set to the `false` and chef is trying to do a `false.any?`. To solve this just set it to `[]`

I review the `CHANGELOG` and there is no note about the breaking change, just that we stop using the `newrelic-infra-integrations` packages. 

Sorry for the confusion, cheers.
