### ISSUE TITLE
newrelic_infra_integration resource needs to support downloads via https_proxy

### ISSUE THREAD

**Issue by haidangwa** [newrelic/infrastructure-agent-chef#58]
We have configured our /etc/chef/client.rb with https_proxy setting, because our nodes are behind a firewall. The only way to download files off the Internet, like https://github.com/newrelic/nri-port-monitor/releases/download/1.2/nri-port-monitor.tar.gz, is to use our https_proxy. However, it appears that the newrelic_infra_integration is not adhering to the chef-client configuration.

I suspect this deficiency has something to do with this [poise_archive resource](https://github.com/newrelic/infrastructure-agent-chef/blob/master/libraries/integration.rb#L93-L97), which doesn't appear to support downloads via https_proxy either. 

The same is true when the `install_method` property of the newrelic_infra_integration resource is given as `binary` (https://github.com/newrelic/infrastructure-agent-chef/blob/master/libraries/integration.rb#L85-L90) -- this block doesn't work through https_proxy either.

## Repro
```
newrelic_infra_integration 'nri-port-monitor' do
  action :create
  bin '/opt/newrelic-infra/nri-port-monitor/bin/port-monitor'
  bin_dir '/opt/newrelic-infra/nri-port-monitor/bin'
  integration_name 'com.newrelic.tcp-port-monitor'
  remote_url 'https://github.com/newrelic/nri-port-monitor/releases/download/1.2/nri-port-monitor.tar.gz'
  commands { metrics: %w[--metrics] }
  instances [
    {
      name: "#{node.name}-nginx-80",
      command: 'metrics',
      arguments: {
        address: '127.0.0.1:80',
        network: 'tcp',
        timeout: 5
      },
      labels: {
        environment: node.chef_environment
      }
    }
  ]
end
```

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
