### ISSUE TITLE
Dependent cookbooks poise-service and poise-archive are archived, not maintained and missing metadata.rb

### ISSUE THREAD

**Issue by MTSimmons** [newrelic/infrastructure-agent-chef#67]
When trying to upload the poise-service and poise-archive cookbooks, I get:

Uploading poise-archive  [0.0.0]
ERROR: The data in your request was invalid
Response: Field 'metadata.name' invalid

Without the poise cookbooks I cannot run this new relic infrastructure cookbook.  I can upload it but if applied to a node I get this in the Run List

Unsatisfiable Run List Item
Unable to satisfy constraints on package poise-service, which does not exist, due to solution constraint (newrelic-infra >= 0.0.0). Solution constraints that may result in a constraint on poise-service: [(newrelic-infra = 0.11.0) -> (poise-service ~> 1.5.0)]

**Comment by junevarsha** [comment]
Yes I noticed this last week and raised an issue: https://github.com/poise/poise-service/issues/53#event-2591729080 - poise service owner closed the repo after this.

Looks like its no longer supported, I had to write a custom chef resource to deal with this problem.

**Comment by MTSimmons** [comment]
If you download poise-service and poise-archive from the Chef Supermarket you can download the complete cookbook, my issue was in part because I was trying to get the code directly from the poise-service GitHub repo. 

I haven't yet tried to upload the cookbook into my chef instance so I'll cross my fingers and hope for the best.  

@junevarsha how did your custom resource do?  Did you end up having to modify the chef-client cookbook?
