### ISSUE TITLE
NewRelic license key insecurely stored

### ISSUE THREAD

**Issue by thedannywilcox** [newrelic/infrastructure-agent-chef#68]
https://github.com/newrelic/infrastructure-agent-chef/blob/0ca47a4a53c58b40d137a5391cf3966d1e156048/recipes/agent_linux.rb#L140

Are there any plans to store the New Relic key in a more secure way? For example, using node.run_state or encrypted data bags?

**Comment by mariomac** [comment]
Hi @thedannywilcox let me forward your suggestion to our team and we will discuss/prioritize it. Thank you!

**Comment by thedannywilcox** [comment]
Hi @mariomac, any update here? Thanks!

**Comment by zelaskov** [comment]
Hi @thedannywilcox, thank you for your idea, much appreciated but the feature you mention is beyond our current roadmap so I close the issue. Thank you for sharing.
