### ISSUE TITLE
Expose the remote_file_attributes and make it sensitive for the windows_package resource in recipes/agent_windows.rb

### ISSUE THREAD

**Issue by emeshuris** [newrelic/infrastructure-agent-chef#70]
hi,
a lot of our machines are not able to connect to external sites to download the artifacts. internally we use artifactory which requires authentication. it is possible to authenticate either through the following two methods:

- HTTPGET header
- basic auth via url with user:pass

both of these methods require that this resource be sensitive.

this is how we had to modify the resource:

```ruby
windows_package 'newrelic-infra' do
  remote_file_attributes ({
    headers: { 'X-Api-Key': node['artifactory']['sa_artifactory_readonly']['api_key'].to_s }
  })
  action :install
  checksum node['newrelic-infra']['windows_checksum']
  installer_type :msi
  retries node['newrelic_infra']['packages']['agent']['retries']
  source node['newrelic-infra']['windows_source']
  sensitive true
end
```

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
