### ISSUE TITLE
the log_file attribute is unusable, it sets on server with double quotes in agent.yaml

### ISSUE THREAD

**Issue by sbhakta99** [newrelic/infrastructure-agent-chef#71]
default['newrelic_infra']['config']['log_file'] = '/app/newrelic-infra/log/newrelic-infra.log'

On Server it puts like this
log_file: "/app/newrelic-infra/log/newrelic-infra.log"

Agent does not startup, it likes it like this:
log_file: /app/newrelic-infra/log/newrelic-infra.log
Then it would start up.

**Comment by sbhakta99** [comment]
Maybe due to following not in quotes?
conf['log_file'] = nil

**Comment by sbhakta99** [comment]
Also the
default['newrelic_infra']['agent']['config']['mode'] = '0644'
This does not work, it doesn't update permission on then agent.yaml

**Comment by sbhakta99** [comment]
Would someone be able to look into these issues?

**Comment by carlosroman** [comment]
Looking into this issues and hopefully should be able to get back you soon.

**Comment by zelaskov** [comment]
hello @sbhakta99, thanks for reporting the issue. I couldn't reproduce your issue with log file - it seems that even if log_file path is in double quotes it works fine.

<img width="446" alt="obraz" src="https://user-images.githubusercontent.com/46314449/123749035-45672580-d8b5-11eb-8839-cc776df4ef29.png">
<img width="780" alt="obraz" src="https://user-images.githubusercontent.com/46314449/123749083-557f0500-d8b5-11eb-891a-0b23084da8fd.png">

and log file is correctly created in specified path.

When it comes to the second part of the issue regarding permissions not correctly passed when creating agent.yaml, I was able to reproduce this bug. There is a PR that should fix it. --> https://github.com/newrelic/infrastructure-agent-chef/pull/83

If that still doesn't work for you, could you include more informations such as OS details and chef version? That could help us with catching this bug.

Everything tested on:
OS: Debian 10
Chef Client 16.10.8
