### ISSUE TITLE
Will there be an enhancement to forward our logs using New Relic Infrastructure?

### ISSUE THREAD

**Issue by sbhakta99** [newrelic/infrastructure-agent-chef#72]
Will there be an enhancement to forward our logs using New Relic Infrastructure?

https://docs.newrelic.com/docs/logs/enable-new-relic-logs/1-enable-logs/forward-your-logs-using-new-relic-infrastructure#parameters

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
