### ISSUE TITLE
ERROR: No candidate version available for newrelic-infra

### ISSUE THREAD

**Issue by gangadhar01a** [newrelic/infrastructure-agent-chef#76]
I am expecting NewRelic cookbook should download and install the latest version of NewRelic infra agent which was not happened. 

**Cookbook attributes:**
default['newrelic_infra']['packages']['agent']['action'] = %i(install)
default['newrelic_infra']['packages']['agent']['retries'] = 1
default['newrelic_infra']['packages']['agent']['version'] = nil

**Compllied Cookbook recipe:**
yum_package("newrelic-infra") do
 package_name "newrelic-infra"
 action [:install]
 default_guard_interpreter :default
 declared_type :package
 cookbook_name "newrelic-infra"
 recipe_name "agent_linux"
 version ""
 retries 1
end

**System Info:**
 ------------
chef_version=15.3.14
platform=centos
platform_version=7.5.1804
ruby=ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]
program_name=/bin/chef-client
executable=/opt/chef/bin/chef-client

**Comment by gangadhar01a** [comment]
Changing the chef client version to 13 has worked. For my knowledge can you please update if the cookbook doesn't support chef client 15?

**Comment by varas** [comment]
Hi @gangadhar01a thanks for reaching us, I added this into our backlog for prioritisation. Thanks!
