### ISSUE TITLE
Support for AWS Graviton ARM instances.

### ISSUE THREAD

**Issue by JaBurd** [newrelic/infrastructure-agent-chef#79]
## Is your feature request related to a problem? Please describe.
With the recent full release of the AWS Graviton ARM based instance types please take up the full support of this architecture.

## Feature Description
Full support of the arm64 processor based infrastructure

## Describe Alternatives
Manual/custom installation

## Priority
Really Want

**Comment by josemore** [comment]
Thanks for submitting this @JaBurd 
The infrastructure agent can be installed on arm64 using the [custom setup](https://docs.newrelic.com/docs/infrastructure/install-configure-manage-infrastructure/linux-installation/install-infrastructure-linux-using-package-manager#custom-setups-tarball).
We are actively working on having proper support for the agent and all on-host integrations, then finally adapting the configuration management setups (chef / ansible / puppet).

**Comment by mileslane** [comment]
Progress?

**Comment by davidgit** [comment]
Hi

I don't have a solution for you  but we're building a new one. You can find the details here: https://github.com/newrelic/chef-install

Would love to hear your thoughts.

Thanks
