### ISSUE TITLE
metadata.rb points to 0.12.0 version on master, but there is no tag

### ISSUE THREAD

**Issue by jurajvsains** [newrelic/infrastructure-agent-chef#94]
I see version 0.12.0 in metadata.rb on master: https://github.com/newrelic/infrastructure-agent-chef/blob/master/metadata.rb#L10

Any reason, why tag 0.12.0 was not created, yet please?

**Comment by zelaskov** [comment]
hello @jurajvsains, we are preparing a new release and I hurried up ;) I will revert this change. https://github.com/newrelic/infrastructure-agent-chef/pull/97
